In [ ]:
import numpy as np
import matplotlib.pylab as plt

In [2]:
#Create 10x2 NumPy array in D
D=np.array([[1.72,0.1],
            [-0.58,0.31],
            [1.99,1.54],
            [1.6,4.97],
            [2.72,2.43],
            [2.83,3.59],
            [5.95,7.71],
            [4.75,7.63],
            [5.57,5.6],
            [9.82,7.91]])

In [3]:
D

array([[ 1.72,  0.1 ],
       [-0.58,  0.31],
       [ 1.99,  1.54],
       [ 1.6 ,  4.97],
       [ 2.72,  2.43],
       [ 2.83,  3.59],
       [ 5.95,  7.71],
       [ 4.75,  7.63],
       [ 5.57,  5.6 ],
       [ 9.82,  7.91]])

In [4]:
#Convariance matrix of D
ConvMatD=np.cov(D.T)
ConvMatD

array([[8.70742333, 7.41923   ],
       [7.41923   , 9.21336556]])

In [5]:
#F is eigenvalues and G is the corresponding eigenvectors
F=np.linalg.eig(ConvMatD)
F

(array([ 1.53685296, 16.38393593]),
 array([[-0.71905385, -0.69495436],
        [ 0.69495436, -0.71905385]]))

In [6]:
v=F[1].T[1]
v

array([-0.69495436, -0.71905385])

In [7]:
result=np.dot(D,v)
result

array([ -1.26722688,   0.18016683,  -2.4903021 ,  -4.68562461,
        -3.63757671,  -4.54812416,  -9.67888362,  -8.78741408,
        -7.89759734, -12.51216776])